# Generated by Django 6.0 on 2025-12-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academy.course",
            ),
            preserve_default=False,
        ),
    ]
