# Generated by Django 6.0 on 2025-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="duration",
            field=models.PositiveIntegerField(default=20, help_text="Хв"),
        ),
    ]
