# Generated by Django 6.0 on 2025-12-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_test_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=1000),
        ),
    ]
